language: go
go:
  - "1.x"
  - "1.9"
  - "1.10.x"
script: |
  set -e

  go install

  mkdir -p $GOPATH/src/github.com/Jille
  git clone --depth=1 https://github.com/Jille/rufs.git $GOPATH/src/github.com/Jille/rufs
  cd $GOPATH/src/github.com/Jille/rufs
  rm -rf vendor
  dep-dl
  go build -v
